/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bkapp.view;

import com.bkapp.dao.SiswaDAO;
import com.bkapp.model.Siswa;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 * @author MyBook Hype AMD
 */
public class PanelDataSiswa extends javax.swing.JPanel {

    /**
     * Creates new form PanelDataSiswa
     */
    public PanelDataSiswa() {
        initComponents();
        loadTable();
    }
    
    private void loadTable() {
        SiswaDAO dao = new SiswaDAO();
        List<Siswa> list = dao.getAllSiswa();
        
        for(Siswa s : list){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_siswa = new javax.swing.JTextField();
        btn_pilihfile = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnNaikKelas = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 24)); // NOI18N
        jLabel3.setText("Input Data Siswa");

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel4.setText("Nis");

        jLabel5.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel6.setText("Kelas");

        jLabel7.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel7.setText("Tahun Ajaran");

        jTextField1.setBackground(new java.awt.Color(110, 203, 246));
        jTextField1.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jTextField2.setBackground(new java.awt.Color(110, 203, 246));
        jTextField2.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(110, 203, 246));
        jTextField3.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(110, 203, 246));
        jTextField4.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.setBorder(null);

        jButton2.setBackground(new java.awt.Color(110, 203, 246));
        jButton2.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jButton2.setText("Edit");
        jButton2.setBorder(null);

        tblData.setAutoCreateRowSorter(true);
        tblData.setBackground(new java.awt.Color(110, 203, 246));
        tblData.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nis", "Nama", "Kelas", "Tahun Ajaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel1.setText("Impor Data Siswa");

        txt_siswa.setBackground(new java.awt.Color(110, 203, 246));
        txt_siswa.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        btn_pilihfile.setBackground(new java.awt.Color(110, 203, 246));
        btn_pilihfile.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        btn_pilihfile.setText("Pilih File");
        btn_pilihfile.setBorder(null);
        btn_pilihfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihfileActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jButton4.setText("Hapus");
        jButton4.setBorder(null);

        btnNaikKelas.setBackground(new java.awt.Color(110, 203, 246));
        btnNaikKelas.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        btnNaikKelas.setText("Naik Kelas");
        btnNaikKelas.setBorder(null);
        btnNaikKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaikKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_pilihfile, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnNaikKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNaikKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_pilihfile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btn_pilihfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihfileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Pilih File Excel Siswa (Nama File = Nama Kelas)");
        chooser.setFileFilter(new FileNameExtensionFilter("Excel File (.xlsx)", "xlsx"));
        
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            
            // 1. LOGIKA PARSING NAMA KELAS DARI FILENAME
            // Contoh Filename: "DATA KELAS X.xlsx - X TJKT 2.xlsx"
            // Kita ambil bagian setelah " - "
            
            String fileName = file.getName(); // Ambil nama file + ekstensi
            String namaKelas = "";
            
            try {
                // Hapus ekstensi .xlsx dulu
                String cleanName = fileName.replace(".xlsx", "");
                
                if (cleanName.contains("-")) {
                    // Ambil teks setelah tanda strip "-"
                    String[] parts = cleanName.split("-");
                    namaKelas = parts[parts.length - 1].trim(); // Ambil bagian terakhir & hapus spasi
                } else {
                    // Jika tidak ada strip, pakai nama file utuh sebagai nama kelas
                    namaKelas = cleanName.trim();
                }
                
                // Konfirmasi ke user apakah nama kelas benar
                int confirm = JOptionPane.showConfirmDialog(this, 
                        "Sistem mendeteksi Kelas dari nama file adalah: \n" + 
                        "[" + namaKelas + "]\n\nLanjutkan import?", 
                        "Konfirmasi Kelas", JOptionPane.YES_NO_OPTION);
                
                if (confirm != JOptionPane.YES_OPTION) return;

                // 2. PROSES BACA EXCEL
                FileInputStream fis = new FileInputStream(file);
                Workbook workbook = new XSSFWorkbook(fis);
                Sheet sheet = workbook.getSheetAt(0);
                
                List<Siswa> listImport = new ArrayList<>();
                int currentYear = Calendar.getInstance().get(Calendar.YEAR); // Angkatan = Tahun Ini
                
                // Loop baris (Mulai dari baris 1, asumsi baris 0 adalah Header)
                for (int i = 1; i <= sheet.getLastRowNum(); i++) {
                    Row row = sheet.getRow(i);
                    if (row == null) continue;
                    
                    // Baca Kolom B (Index 1) -> NIS
                    Cell cellNis = row.getCell(1);
                    if (cellNis == null) continue;
                    
                    String nis = "";
                    if (cellNis.getCellType() == CellType.NUMERIC) {
                        nis = String.valueOf((long)cellNis.getNumericCellValue());
                    } else {
                        nis = cellNis.getStringCellValue();
                    }
                    
                    // Baca Kolom C (Index 2) -> Nama
                    Cell cellNama = row.getCell(2);
                    String nama = (cellNama != null) ? cellNama.getStringCellValue() : "-";
                    
                    // Buat Object Siswa
                    Siswa s = new Siswa();
                    s.setNis(nis);
                    s.setNamaSiswa(nama);
                    s.setKelas(namaKelas); // Set Kelas dari Nama File tadi
                    s.setAngkatan(currentYear);
                    
                    listImport.add(s);
                }
                
                // 3. KIRIM KE DATABASE
                SiswaDAO dao = new SiswaDAO();
                dao.importSiswaBatch(listImport);
                
                JOptionPane.showMessageDialog(this, "Selesai! " + listImport.size() + " data diproses.");
                loadTable();
                
                workbook.close();
                fis.close();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Import: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_pilihfileActionPerformed

    private void btnNaikKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaikKelasActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "PERHATIAN KERAS!\n\n" +
            "1. Siswa Kelas XII akan DIHAPUS (Lulus).\n" +
            "2. Siswa Kelas XI akan naik ke XII.\n" +
            "3. Siswa Kelas X akan naik ke XI.\n\n" +
            "Pastikan Anda sudah mem-backup data atau mencetak laporan sebelum melanjutkan.\n" +
            "Lanjutkan proses?", 
            "Konfirmasi Tahun Ajaran Baru", 
            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
        if (confirm == JOptionPane.YES_OPTION) {
            SiswaDAO dao = new SiswaDAO();
            if (dao.prosesKenaikanKelas()) {
                JOptionPane.showMessageDialog(this, "Selamat! Proses kenaikan kelas selesai.");
                loadTable();
            }
        }
    }//GEN-LAST:event_btnNaikKelasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNaikKelas;
    private javax.swing.JButton btn_pilihfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txt_siswa;
    // End of variables declaration//GEN-END:variables
}
