    /*
     * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
     * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
     */
    package com.bkapp.view;

    import com.bkapp.dao.SiswaDAO;
    import com.bkapp.model.Siswa;

    import java.util.List;
    import javax.swing.table.DefaultTableModel;


    public class PanelHome extends javax.swing.JPanel {

        /**
         * Creates new form PanelHome
         */
        public PanelHome() {
            initComponents();

            isiTableNotifikasi();
        }

        private void isiTableNotifikasi() {
            SiswaDAO dao = new SiswaDAO();
            List<Siswa> listSiswa = dao.getSiswaBermasalah();
            DefaultTableModel model = (DefaultTableModel) tblNotifikasi.getModel();
            model.setRowCount(0);

            for (Siswa s : listSiswa) {
                String status;
                if (s.getTotalPoin() >= 100) {
                    status = "DROP OUT / KELUARKAN";
                } else {
                    status = "SURAT PERINGATAN (SP)";
                }

                Object[] row = {
                        s.getNamaSiswa(),
                        s.getKelas(),
                        s.getTotalPoin(),
                        status
                };
                model.addRow(row);
            }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            tblNotifikasi = new javax.swing.JTable();
            jLabel2 = new javax.swing.JLabel();

            setLayout(new java.awt.CardLayout());

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));

            jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 24)); // NOI18N
            jLabel1.setText("Aplikasi Pemantauan Siswa Bimbingan Konseling");

            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoresize.png"))); // NOI18N

            tblNotifikasi.setBackground(new java.awt.Color(110, 203, 246));
            tblNotifikasi.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
            tblNotifikasi.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null}
                    },
                    new String[]{
                            "Nama siswa", "Kelas", "Total poin", "Status"
                    }
            ) {
                Class[] types = new Class[]{
                        java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                        false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            tblNotifikasi.setEnabled(false);
            jScrollPane1.setViewportView(tblNotifikasi);

            jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
            jLabel2.setText("Notifikasi");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel2)
                                    .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)
                                    .addGap(7, 7, 7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                    .addGap(30, 30, 30))
            );

            add(jPanel1, "card2");
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tblNotifikasi;
        // End of variables declaration//GEN-END:variables
    }
