package com.bkapp.view;
import java.io.File;
import javax.swing.JFileChooser;
import com.bkapp.dao.*;
import com.bkapp.model.*;
import java.nio.file.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

public class PanelPelanggaran extends javax.swing.JPanel {

    // Variabel global untuk menyimpan file foto sementara
    private File fileFotoDipilih = null;
    
    // Variabel User yang sedang login (Nanti dioper dari Dashboard)
    // Untuk sementara kita hardcode ID = 1 (Admin BK)
    private int idUserLogin = 1;
    
    public PanelPelanggaran() {
        initComponents();
        initForm();
    }
    
    private void initForm() {
        // 1. Isi Dropdown Jenis Pelanggaran
        MasterDAO masterDao = new MasterDAO();
        List<Pelanggaran> listPel = masterDao.getAllPelanggaran();
        
        cbJenisPelanggaran.removeAllItems();
        cbJenisPelanggaran.addItem("-- Pilih Pelanggaran --");
        for (Pelanggaran p : listPel) {
            cbJenisPelanggaran.addItem(p); // Ini akan memanggil toString() otomatis
        }
        
        // 2. Isi Dropdown Kelas
        SiswaDAO siswaDao = new SiswaDAO();
        List<String> listKelas = siswaDao.getAllKelas();
        
        cbKelas.removeAllItems();
        cbKelas.addItem("-- Pilih Kelas --");
        for (String k : listKelas) {
            cbKelas.addItem(k);
        }
        
        // Matikan textfield agar Read-Only sesuai permintaan
        txtSanksi.setEditable(false);
        txtTotalPoin.setEditable(false); // Atau txtPoinPelanggaran
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sss = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbKelas = new javax.swing.JComboBox();
        cbNamaSiswa = new javax.swing.JComboBox();
        cbJenisPelanggaran = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSanksi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotalPoin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFoto = new javax.swing.JTextField();
        btn_pilihfoto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPoinInput = new javax.swing.JTextField();

        sss.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("as");

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel3.setText("Pilih Kelas");

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel4.setText("Pilih Nama");

        jLabel5.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel5.setText("Pilih Jenis Pelanggaran");

        jLabel6.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel6.setText("Sanksi");

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(110, 203, 246));
        jButton2.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jButton2.setText("Edit");
        jButton2.setBorder(null);

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbKelas.setBackground(new java.awt.Color(110, 203, 246));
        cbKelas.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        cbKelas.setBorder(null);
        cbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelasActionPerformed(evt);
            }
        });

        cbNamaSiswa.setBackground(new java.awt.Color(110, 203, 246));
        cbNamaSiswa.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        cbNamaSiswa.setBorder(null);
        cbNamaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamaSiswaActionPerformed(evt);
            }
        });

        cbJenisPelanggaran.setBackground(new java.awt.Color(110, 203, 246));
        cbJenisPelanggaran.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        cbJenisPelanggaran.setBorder(null);
        cbJenisPelanggaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisPelanggaranActionPerformed(evt);
            }
        });

        txtSanksi.setEditable(false);
        txtSanksi.setBackground(new java.awt.Color(110, 203, 246));
        txtSanksi.setColumns(20);
        txtSanksi.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        txtSanksi.setLineWrap(true);
        txtSanksi.setRows(3);
        txtSanksi.setTabSize(7);
        txtSanksi.setWrapStyleWord(true);
        txtSanksi.setAutoscrolls(false);
        txtSanksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtSanksi);

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 24)); // NOI18N
        jLabel1.setText("Form Poin Pelanggaran");

        tblRiwayat.setBackground(new java.awt.Color(110, 203, 246));
        tblRiwayat.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Kode Pelanggaran", "Jenis Pelanggaran", "Poin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRiwayat);

        jLabel8.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        jLabel8.setText("Riwayat Pelanggaran");

        jLabel9.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel9.setText("Total Poin");

        txtTotalPoin.setEditable(false);
        txtTotalPoin.setBackground(new java.awt.Color(110, 203, 246));
        txtTotalPoin.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        txtTotalPoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPoinActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel10.setText("Input Foto");

        txtFoto.setBackground(new java.awt.Color(110, 203, 246));
        txtFoto.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        txtFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFotoActionPerformed(evt);
            }
        });

        btn_pilihfoto.setBackground(new java.awt.Color(110, 203, 246));
        btn_pilihfoto.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        btn_pilihfoto.setText("Pilih File");
        btn_pilihfoto.setBorder(null);
        btn_pilihfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihfotoActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(153, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Preview");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel11.setText("Poin");

        txtPoinInput.setEditable(false);
        txtPoinInput.setBackground(new java.awt.Color(110, 203, 246));
        txtPoinInput.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        javax.swing.GroupLayout sssLayout = new javax.swing.GroupLayout(sss);
        sss.setLayout(sssLayout);
        sssLayout.setHorizontalGroup(
            sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sssLayout.createSequentialGroup()
                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sssLayout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jLabel1))
                    .addGroup(sssLayout.createSequentialGroup()
                        .addGap(813, 813, 813)
                        .addComponent(jLabel2))
                    .addGroup(sssLayout.createSequentialGroup()
                        .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sssLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(sssLayout.createSequentialGroup()
                                        .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(sssLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(104, 104, 104)
                                                .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(sssLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(100, 100, 100)
                                                .addComponent(cbNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(29, 29, 29)
                                        .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(sssLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTotalPoin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(sssLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPoinInput, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(sssLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(34, 34, 34)
                                        .addComponent(cbJenisPelanggaran, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(sssLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sssLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(sssLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18))
                                    .addGroup(sssLayout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)))
                                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sssLayout.createSequentialGroup()
                                        .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_pilihfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sssLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sssLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel8)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        sssLayout.setVerticalGroup(
            sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sssLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(txtPoinInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalPoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbJenisPelanggaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pilihfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sssLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(sssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sssLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(sssLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pilihfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihfotoActionPerformed
        JFileChooser chooser = new JFileChooser();

        // Hanya file (bukan folder)
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // Filter hanya gambar
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Gambar (JPG, PNG)", "jpg", "jpeg", "png"
        ));

        int hasil = chooser.showOpenDialog(this);

        if (hasil == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            
            // TAMBAHKAN BARIS INI (PENTING!)
            this.fileFotoDipilih = file; 

            txtFoto.setText(file.getAbsolutePath());
            
            // (Opsional) Fitur Preview Foto
            try {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(file.getAbsolutePath());
                // Resize gambar agar muat di label
                java.awt.Image img = icon.getImage().getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), java.awt.Image.SCALE_SMOOTH);
                jLabel7.setIcon(new javax.swing.ImageIcon(img));
                jLabel7.setText(""); // Hapus tulisan "Preview"
            } catch (Exception e) {
                //baikan jika error preview
            }
        }
    }//GEN-LAST:event_btn_pilihfotoActionPerformed

    private void txtFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFotoActionPerformed

    private void cbJenisPelanggaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisPelanggaranActionPerformed
        if (cbJenisPelanggaran.getSelectedItem() instanceof Pelanggaran) {
            Pelanggaran p = (Pelanggaran) cbJenisPelanggaran.getSelectedItem();

            // Isi Textfield Sanksi (Read Only)
            txtSanksi.setText(p.getSanksi());

            // Isi Poin (Read Only) - Misal nama fieldnya txtPoinInput
            txtPoinInput.setText(String.valueOf(p.getPoin()));
        }
    }//GEN-LAST:event_cbJenisPelanggaranActionPerformed

    private void cbNamaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamaSiswaActionPerformed
        // Pastikan yang dipilih adalah Object Siswa (bukan null)
        if (cbNamaSiswa.getSelectedItem() instanceof Siswa) {
            Siswa s = (Siswa) cbNamaSiswa.getSelectedItem();

            // Tampilkan data poin siswa saat ini di label/textfield jika ada
            txtTotalPoin.setText(String.valueOf(s.getTotalPoin()));

            // Refresh Tabel Kanan
            HistoriDAO historiDao = new HistoriDAO();
            // tblRiwayat adalah nama tabel di kanan (sesuaikan variabel Anda)
            tblRiwayat.setModel(historiDao.getHistoriTable(s.getIdSiswa()));
        }
    }//GEN-LAST:event_cbNamaSiswaActionPerformed

    private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
        if (cbKelas.getSelectedItem() == null || cbKelas.getSelectedIndex() == 0) return;

        String kelasTerpilih = cbKelas.getSelectedItem().toString();

        SiswaDAO dao = new SiswaDAO();
        List<Siswa> listSiswa = dao.getSiswaByKelas(kelasTerpilih);

        cbNamaSiswa.removeAllItems(); // Pastikan variabelnya cbNamaSiswa (sesuaikan punya Anda)
        for (Siswa s : listSiswa) {
            cbNamaSiswa.addItem(s); // toString() siswa akan tampil "NIS - Nama"
        }
    }//GEN-LAST:event_cbKelasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!(cbNamaSiswa.getSelectedItem() instanceof Siswa)) {
            JOptionPane.showMessageDialog(this, "Pilih Siswa dulu!");
            return;
        }
        if (!(cbJenisPelanggaran.getSelectedItem() instanceof Pelanggaran)) {
            JOptionPane.showMessageDialog(this, "Pilih Jenis Pelanggaran!");
            return;
        }
        // Foto boleh kosong atau wajib? Misal wajib:
        if (fileFotoDipilih == null) {
            JOptionPane.showMessageDialog(this, "Harap upload bukti foto!");
            return;
        }

        // AMBIL DATA
        Siswa siswa = (Siswa) cbNamaSiswa.getSelectedItem();
        Pelanggaran pel = (Pelanggaran) cbJenisPelanggaran.getSelectedItem();

        // 1. PROSES UPLOAD FOTO
        String pathDB = "";
        try {
            String appPath = System.getProperty("user.dir");
            File folder = new File(appPath + File.separator + "bukti_bk");
            if (!folder.exists()) folder.mkdirs();

            String namaFile = siswa.getNis() + "_" + System.currentTimeMillis() + ".jpg";
            Path source = fileFotoDipilih.toPath();
            Path target = Paths.get(folder.getAbsolutePath() + File.separator + namaFile);

            Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
            pathDB = target.toString();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Upload Foto: " + e.getMessage());
            return;
        }

        // 2. SIMPAN KE DATABASE (Histori & Update Poin)
        HistoriDAO hDao = new HistoriDAO();
        SiswaDAO sDao = new SiswaDAO();

        boolean suksesHistori = hDao.insertPelanggaran(siswa.getIdSiswa(), pel.getKodePelanggaran(), idUserLogin, pathDB);

        if (suksesHistori) {
            // Update total poin siswa (Poin Lama + Poin Pelanggaran Baru)
            int poinBaru = siswa.getTotalPoin() + pel.getPoin();
            sDao.updatePoinSiswa(siswa.getIdSiswa(), poinBaru);

            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan! Poin bertambah.");

            // Reset Form atau Refresh Tabel
            cbNamaSiswaActionPerformed(null); // Refresh tabel riwayat
            fileFotoDipilih = null;
            // lblPreviewFoto.setIcon(null); // Kosongkan preview jika ada
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotalPoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPoinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pilihfoto;
    private javax.swing.JComboBox cbJenisPelanggaran;
    private javax.swing.JComboBox cbKelas;
    private javax.swing.JComboBox cbNamaSiswa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel sss;
    private javax.swing.JTable tblRiwayat;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextField txtPoinInput;
    private javax.swing.JTextArea txtSanksi;
    private javax.swing.JTextField txtTotalPoin;
    // End of variables declaration//GEN-END:variables
}
